name: python-solver
version: 1.0.0
entrypoint: run.py
allowed_systems:
- dev-system
- hpc-cluster-01
- sci-slurm-lammps
parser_config: parser_config.yaml
metrics:
- name: runtime_seconds
  unit: s
  required: true
log_names:
- stdout
default_system: dev-system
