patterns:
  - name: Total mass
    regex: 'Total mass \s*([\d.e+-]+)'
    type: float
  - name: runtime_seconds
    regex: 'runtime_seconds:\s*([\d.]+)'
    type: float
  - name: n_atoms
    regex: '\s*(\d+) atoms'
    type: int
  - name: potential_energy_kj_mol
    regex: 'Potential Energy\s+=\s+([-\d.e+]+)'
    type: float
  - name: Total MFlops
    regex: 'Total\s+([\d,]+\.[\d]+)'
    type: float
