name: gromacs-solver
version: "1.0.0"
entrypoint: run.sh
allowed_systems: [dev-system, gromacs-docker]
default_system: gromacs-docker
parser_config: parser_config.yaml
metrics:
  - name: Total mass
    unit: amu
    min: 1
    required: true
  - name: runtime_seconds
    unit: s
    required: true
  - name: n_atoms
    unit: count
    required: true
  - name: potential_energy_kj_mol
    unit: kj/mol
  - name: Total MFlops
    unit: mflops
log_names: [stdout]
