name: echo-solver
version: 1.0.0
entrypoint: run.sh
allowed_systems:
- dev-system
- hpc-cluster-01
- sci-slurm-lammps
parser_config: parser_config.yaml
metrics:
- name: solver_finished
  required: true
log_names: []
default_system: dev-system
