name: gromacs-local
version: "1.0.0"
entrypoint: run.sh
allowed_systems: [dev-system, hpc-cluster-01]
default_system: dev-system
parser_config: parser_config.yaml
metrics:
  - name: Total mass
    unit: amu
    min: 1
    required: true
  - name: runtime_seconds
    unit: s
    required: true
  - name: potential_energy_kj_mol
    unit: kJ/mol
    required: true
  - name: n_atoms
    unit: count
    required: true
log_names: [stdout]
